version: "2.1"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: k2j32ks4    
    ports:
      - 3306:3306
    volumes:
      - ../db:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysql --user=root --password=k2j32ks4 -e 'SHOW DATABASES'
      timeout: 20s
      retries: 10
    networks:
      - greatquotes

  adminer:
    image: adminer
    ports:
      - 8085:8080
    depends_on:
      - db
    networks:
      - greatquotes

  api:
    build: ../api/
    ports:
      - 8090:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - greatquotes

  app:
    build: ../app/
    ports:
      - 85:3000
    depends_on:
      - api
    networks:
      - greatquotes

networks:
  greatquotes:
    driver: bridge
