version: "3.1"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: k2j32ks4
    ports:
      - 3306:3306
    volumes:
      - ../db:/docker-entrypoint-initdb.d
    networks:
      - greatquotes

  adminer:
    image: adminer
    ports:
      - 8085:8080
    depends_on:
      - mysql
    networks:
      - greatquotes

  backend:
    build: ../backend/
    ports:
      - 8090:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 1s
      timeout: 3s
      retries: 60
    depends_on:
      - mysql
    networks:
      - greatquotes

  frontend:
    build: ../frontend/
    ports:
      - 85:3000
    depends_on:
      - backend
    networks:
      - greatquotes

networks:
  greatquotes:
    driver: bridge
