version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: k2j32ks4
    ports:
          - 3306:3306
    volumes:
      - ../db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

#  server:
#    image: openjdk:8-jre-alpine
#    restart: always
#    depends_on:
#      - db
#    volumes:
#      - ./grpc:/home
#    entrypoint: ["java", "-jar", "bla.jar"]


